# Configuração de chunking para indexação de PDFs
# 'paragraph' usa parágrafos como chunks. 'words' usa número máximo de palavras por chunk
findinpdf.chunk.mode=words

# Define o número máximo de palavras por chunk quando o modo é 'words'.
findinpdf.chunk.max-words=500
